//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/UniversalInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UniversalInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UniversalInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UniversalInput"",
    ""maps"": [
        {
            ""name"": ""Mighty"",
            ""id"": ""77531062-da48-4377-bfee-3cb7bfd71a60"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""52d8d04a-ef00-4d10-b1cb-75d14eecc529"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""ad4060cd-1f8b-442b-b596-29030e155ab7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""501457ac-f6e3-4584-9140-d4e26c247812"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Melee"",
                    ""type"": ""Button"",
                    ""id"": ""49921be3-7265-448e-9adb-0dbe2dc02b61"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""bc52fb52-9ba7-4c1e-a9ec-af2da62586b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change"",
                    ""type"": ""Button"",
                    ""id"": ""8a2428d3-c75a-4088-9314-69d827fb9a0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""709733ab-ff70-4c5b-8362-8699bb15a717"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5b07ef7d-3f00-463c-9da8-c83ae1f72b6f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""93c7e9df-474c-42cc-86a6-ac5765226573"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5bf42db0-f18b-4f2b-8e03-cb7da06adf0c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c1fc303e-2fe5-4149-8881-303e6fbda1e2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""515b27a8-d9d3-49dd-a209-d0a5401dd3c7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7636aaae-3fc4-4aaf-a25f-92b2a1341c99"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fe9ad07-c3e6-43b3-8c82-d57d51aa231e"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6fab7be8-b028-45b5-921e-465a6143c9b6"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Melee"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""037d2880-04de-46cd-a1aa-ecdd5a7cbdcf"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f32da1d-8511-4208-92ef-78c3ea82bf2e"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19e9052f-9ae5-43f5-bf88-bdaddece4905"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Mighty
        m_Mighty = asset.FindActionMap("Mighty", throwIfNotFound: true);
        m_Mighty_Movement = m_Mighty.FindAction("Movement", throwIfNotFound: true);
        m_Mighty_Shoot = m_Mighty.FindAction("Shoot", throwIfNotFound: true);
        m_Mighty_Dash = m_Mighty.FindAction("Dash", throwIfNotFound: true);
        m_Mighty_Melee = m_Mighty.FindAction("Melee", throwIfNotFound: true);
        m_Mighty_Jump = m_Mighty.FindAction("Jump", throwIfNotFound: true);
        m_Mighty_Change = m_Mighty.FindAction("Change", throwIfNotFound: true);
        m_Mighty_Reset = m_Mighty.FindAction("Reset", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Mighty
    private readonly InputActionMap m_Mighty;
    private IMightyActions m_MightyActionsCallbackInterface;
    private readonly InputAction m_Mighty_Movement;
    private readonly InputAction m_Mighty_Shoot;
    private readonly InputAction m_Mighty_Dash;
    private readonly InputAction m_Mighty_Melee;
    private readonly InputAction m_Mighty_Jump;
    private readonly InputAction m_Mighty_Change;
    private readonly InputAction m_Mighty_Reset;
    public struct MightyActions
    {
        private @UniversalInput m_Wrapper;
        public MightyActions(@UniversalInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Mighty_Movement;
        public InputAction @Shoot => m_Wrapper.m_Mighty_Shoot;
        public InputAction @Dash => m_Wrapper.m_Mighty_Dash;
        public InputAction @Melee => m_Wrapper.m_Mighty_Melee;
        public InputAction @Jump => m_Wrapper.m_Mighty_Jump;
        public InputAction @Change => m_Wrapper.m_Mighty_Change;
        public InputAction @Reset => m_Wrapper.m_Mighty_Reset;
        public InputActionMap Get() { return m_Wrapper.m_Mighty; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MightyActions set) { return set.Get(); }
        public void SetCallbacks(IMightyActions instance)
        {
            if (m_Wrapper.m_MightyActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_MightyActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_MightyActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_MightyActionsCallbackInterface.OnMovement;
                @Shoot.started -= m_Wrapper.m_MightyActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_MightyActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_MightyActionsCallbackInterface.OnShoot;
                @Dash.started -= m_Wrapper.m_MightyActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_MightyActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_MightyActionsCallbackInterface.OnDash;
                @Melee.started -= m_Wrapper.m_MightyActionsCallbackInterface.OnMelee;
                @Melee.performed -= m_Wrapper.m_MightyActionsCallbackInterface.OnMelee;
                @Melee.canceled -= m_Wrapper.m_MightyActionsCallbackInterface.OnMelee;
                @Jump.started -= m_Wrapper.m_MightyActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_MightyActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_MightyActionsCallbackInterface.OnJump;
                @Change.started -= m_Wrapper.m_MightyActionsCallbackInterface.OnChange;
                @Change.performed -= m_Wrapper.m_MightyActionsCallbackInterface.OnChange;
                @Change.canceled -= m_Wrapper.m_MightyActionsCallbackInterface.OnChange;
                @Reset.started -= m_Wrapper.m_MightyActionsCallbackInterface.OnReset;
                @Reset.performed -= m_Wrapper.m_MightyActionsCallbackInterface.OnReset;
                @Reset.canceled -= m_Wrapper.m_MightyActionsCallbackInterface.OnReset;
            }
            m_Wrapper.m_MightyActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Melee.started += instance.OnMelee;
                @Melee.performed += instance.OnMelee;
                @Melee.canceled += instance.OnMelee;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Change.started += instance.OnChange;
                @Change.performed += instance.OnChange;
                @Change.canceled += instance.OnChange;
                @Reset.started += instance.OnReset;
                @Reset.performed += instance.OnReset;
                @Reset.canceled += instance.OnReset;
            }
        }
    }
    public MightyActions @Mighty => new MightyActions(this);
    public interface IMightyActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnMelee(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnChange(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
    }
}
